/*
 * Translation table - automatically generated by po2table.sh.
 */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
#include <string.h>

struct msgtable_s {
	char *msgid;
	char *msgstr;
};


struct msgtable_s *minigettext__gettable(char *lang)
{
	if (lang == 0)
		return 0;

	if (strncmp(lang, "de", 2) == 0) {
		static struct msgtable_s data[] = {
			{
				""
			,
				""
				"Report-Msgid-Bugs-To: \n"
				"POT-Creation-Date: 2010-12-14 10:06+0000\n"
				"Content-Type: text/plain; charset=iso-8859-15\n"
				"Date: 1999-06-01 15:18:29+0100\n"
				"From: Andrew Wood <ivarch@ubik>\n"
				"Xgettext-Options: --default-domain=pkgbuild --directory=./.pkgdir --add-"
				"comments --keyword=_ --keyword=N_\n"
				"Files: src/getopt/getopt.c src/getopt/getopt1.c src/version.c src/main/init."
				"c src/main/help.c src/main/xpmptr.c src/guts/load.c src/guts/stop.c src/guts/"
				"configure.c src/guts/make.c src/guts/install.c src/guts/prefs.c src/ui/"
				"generate.c src/ui/main.c src/ui/xpm.c src/ui/status.c src/ui/activate.c src/"
				"ui/handlers/main.c src/ui/handlers/package.c src/ui/handlers/prefs.c src/ui/"
				"handlers/dirsel.c src/ui/handlers/popup.c src/ui/handlers/help.c src/ui/"
				"textout.c src/ui/report.c src/ui/callback.c src/nls/intl/bindtextdom.c src/"
				"nls/intl/dcgettext.c src/nls/intl/dgettext.c src/nls/intl/finddomain.c src/"
				"nls/intl/gettext.c src/nls/intl/loadmsgcat.c src/nls/intl/localealias.c src/"
				"nls/intl/textdomain.c src/nls/intl-cat/cat-compat.c src/nls/intl-gett/intl-"
				"compat.c\n"
			}, 
			{
				"failed to close file"
			,
				"Datei konnte nicht geschlossen werden"
			}, 
			{
				"failed to read file"
			,
				"Datei konnte nicht gelesen werden"
			}, 
			{
				"failed to stat file"
			,
				"Dateiinformationen konnten nicht gelesen werden"
			}, 
			{
				"failed to stat output file"
			,
				"Dateiinformationen für Ausgabe-Datei konnten nicht gelesen werden"
			}, 
			{
				"input file is output file"
			,
				"Eingabe-Datei ist Ausgabe-Datei"
			}, 
			{
				"yzafpnum kMGTPEZY"
			,
				""
			}, 
			{
				"buffer allocation failed"
			,
				"Puffer konnte nicht allokiert werden"
			}, 
			{
				"B"
			,
				"B"
			}, 
			{
				"/s"
			,
				""
			}, 
			{
				"B/s"
			,
				""
			}, 
			{
				"ETA"
			,
				"ETA"
			}, 
			{
				"failed to open terminal"
			,
				"Terminal konnte nicht geöffnet werden"
			}, 
			{
				"failed to lock terminal"
			,
				"Terminal konnte nicht geöffnet werden"
			}, 
			{
				"select call failed"
			,
				"select-Aufruf fehlgeschlagen"
			}, 
			{
				"read failed"
			,
				"read-Aufruf fehlgeschlagen"
			}, 
			{
				"write failed"
			,
				"write-Aufruf fehlgeschlagen"
			}, 
			{
				"show progress bar"
			,
				"Fortschritts-Anzeige"
			}, 
			{
				"show elapsed time"
			,
				"zeige die verstrichene Zeit an"
			}, 
			{
				"show estimated time of arrival (completion)"
			,
				"zeige die erwartete Zeit bis zum Ende an"
			}, 
			{
				"show data transfer rate counter"
			,
				"zeige die Datentransferrate an"
			}, 
			{
				"show data transfer average rate counter"
			,
				""
			}, 
			{
				"show number of bytes transferred"
			,
				"zeige die Anzahl von Bytes, die transferiert worden sind"
			}, 
			{
				"output even if standard error is not a terminal"
			,
				""
				"Ausgabe auch dann erzwingen, wenn der Fehlerausgabe-Kanal kein Terminal ist"
			}, 
			{
				"output percentages, not visual information"
			,
				"Ausgabe von Prozent-Angaben statt visueller Darstellung"
			}, 
			{
				"do not output any transfer information at all"
			,
				"sämtliche Transferinformationen unterdrücken"
			}, 
			{
				"use cursor positioning escape sequences"
			,
				"benutze Escape-Sequenzen zur Cursor-Positionierung"
			}, 
			{
				"display nothing until first byte transferred"
			,
				"keine Ausgabe bevor das erste Byte übertragen wurde"
			}, 
			{
				"SIZE"
			,
				""
			}, 
			{
				"set estimated data size to SIZE bytes"
			,
				"setze erwartete Daten-Länge auf SIZE Byte"
			}, 
			{
				"count lines instead of bytes"
			,
				""
			}, 
			{
				"SEC"
			,
				""
			}, 
			{
				"update every SEC seconds"
			,
				"aktualisiere Ausgabe nach SEC Sekunden Intervall"
			}, 
			{
				"WIDTH"
			,
				""
			}, 
			{
				"assume terminal is WIDTH characters wide"
			,
				"setze Terminal-Breite auf WIDTH Zeichen"
			}, 
			{
				"HEIGHT"
			,
				""
			}, 
			{
				"assume terminal is HEIGHT rows high"
			,
				"setze Terminal-Breite auf WIDTH Zeichen"
			}, 
			{
				"NAME"
			,
				""
			}, 
			{
				"prefix visual information with NAME"
			,
				"setze den NAMEn für visuelle Darstellung"
			}, 
			{
				"RATE"
			,
				""
			}, 
			{
				"limit transfer to RATE bytes per second"
			,
				"beschränke die Transferrate auf RATE Byte pro Sekunde"
			}, 
			{
				"BYTES"
			,
				""
			}, 
			{
				"use a buffer size of BYTES"
			,
				""
			}, 
			{
				"PID"
			,
				""
			}, 
			{
				"update settings of process PID"
			,
				""
			}, 
			{
				"show this help and exit"
			,
				"zeige diese Hilfe und beende"
			}, 
			{
				"show version information and exit"
			,
				"zeige Versionsinformationen und beende"
			}, 
			{
				"Usage: %s [OPTION] [FILE]..."
			,
				"Syntax: %s [OPTION] [DATEI]..."
			}, 
			{
				""
				"Concatenate FILE(s), or standard input, to standard output,\n"
				"with monitoring."
			,
				""
				"Verbindet DATEI(en) oder den Standard-Eingabe-Kanal mit dem\n"
				"Standard-Ausgabe-Kanal und misst den Datenstrom."
			}, 
			{
				"Please report any bugs to %s."
			,
				"Bitte senden Sie Fehlerberichte an %s."
			}, 
			{
				"%s: option structure allocation failed (%s)"
			,
				"%s: `option' konnte nicht allokiert werden (%s)"
			}, 
			{
				"%s: option structure argv allocation failed (%s)"
			,
				"%s: `option' (argv) konnte nicht allokiert werden (%s)"
			}, 
			{
				"integer argument expected"
			,
				""
			}, 
			{
				"numeric argument expected"
			,
				""
			}, 
			{
				"Try `%s --help' for more information."
			,
				"`%s --help' zeigt weitere Informationen an."
			}, 
			{
				"Try `%s -h' for more information."
			,
				"`%s -h' zeigt weitere Informationen an."
			}, 
			{
				"%s %s - Copyright(C) %s %s"
			,
				"%s %s - Copyright(C) %s %s"
			}, 
			{
				"Web site: %s"
			,
				"Web-Site: %s"
			}, 
			{
				""
				"This program is free software, and is being distributed under the\n"
				"terms of the Artistic License 2.0."
			,
				""
				"Dieses Programm ist freie Software und wird unter den Bedingungen\n"
				"der Artistic License verbreitet."
			}, 
			{
				""
				"This program is distributed in the hope that it will be useful,\n"
				"but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
				"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
			,
				""
				"Dieses Programm wird verbreitet unter der Annahme dass es nützlich ist,\n"
				"aber OHNE JEGLICHE GARANTIE; insbesondere ohne der impliziten Garantie\n"
				"einer MARKTGÄNGIGKEIT oder EIGNUNG ZU EINEM BESTIMMTEN ZWECK."
			}

			, { 0, 0 } };
		return data;
	}
	if (strncmp(lang, "fr", 2) == 0) {
		static struct msgtable_s data[] = {
			{
				""
			,
				""
				"Report-Msgid-Bugs-To: \n"
				"POT-Creation-Date: 2010-12-14 10:06+0000\n"
				"Content-Type: text/plain; charset=ISO-8859-15\n"
				"Date: 1999-06-01 15:18:29+0100\n"
				"From: Andrew Wood <ivarch@ubik>\n"
				"Xgettext-Options: --default-domain=pkgbuild --directory=./.pkgdir --add-"
				"comments --keyword=_ --keyword=N_\n"
				"Files: src/getopt/getopt.c src/getopt/getopt1.c src/version.c src/main/init."
				"c src/main/help.c src/main/xpmptr.c src/guts/load.c src/guts/stop.c src/guts/"
				"configure.c src/guts/make.c src/guts/install.c src/guts/prefs.c src/ui/"
				"generate.c src/ui/main.c src/ui/xpm.c src/ui/status.c src/ui/activate.c src/"
				"ui/handlers/main.c src/ui/handlers/package.c src/ui/handlers/prefs.c src/ui/"
				"handlers/dirsel.c src/ui/handlers/popup.c src/ui/handlers/help.c src/ui/"
				"textout.c src/ui/report.c src/ui/callback.c src/nls/intl/bindtextdom.c src/"
				"nls/intl/dcgettext.c src/nls/intl/dgettext.c src/nls/intl/finddomain.c src/"
				"nls/intl/gettext.c src/nls/intl/loadmsgcat.c src/nls/intl/localealias.c src/"
				"nls/intl/textdomain.c src/nls/intl-cat/cat-compat.c src/nls/intl-gett/intl-"
				"compat.c\n"
			}, 
			{
				"failed to close file"
			,
				"la fermeture du fichier a échoué"
			}, 
			{
				"failed to read file"
			,
				"la lecture du fichier a échoué"
			}, 
			{
				"failed to stat file"
			,
				"échec à statuer sur le fichier"
			}, 
			{
				"failed to stat output file"
			,
				"échec à statuer sur le fichier de sortie"
			}, 
			{
				"input file is output file"
			,
				"fichiers d'entré et de sortie sont les mêmes"
			}, 
			{
				"yzafpnum kMGTPEZY"
			,
				""
			}, 
			{
				"buffer allocation failed"
			,
				"l'allocation de mémoire tampon a échoué"
			}, 
			{
				"B"
			,
				"O"
			}, 
			{
				"/s"
			,
				"/s"
			}, 
			{
				"B/s"
			,
				"O/s"
			}, 
			{
				"ETA"
			,
				"ETA"
			}, 
			{
				"failed to open terminal"
			,
				"l'ouverture du terminal a échoué"
			}, 
			{
				"failed to lock terminal"
			,
				"l'ouverture du terminal a échoué"
			}, 
			{
				"select call failed"
			,
				"appel de sélection a échoué"
			}, 
			{
				"read failed"
			,
				"la lecture a échoué"
			}, 
			{
				"write failed"
			,
				"l'écriture a échoué"
			}, 
			{
				"show progress bar"
			,
				"affiche la barre de progression"
			}, 
			{
				"show elapsed time"
			,
				"affiche le temps écoulé"
			}, 
			{
				"show estimated time of arrival (completion)"
			,
				"affiche l'heure approximative de l'achèvement de la tâche"
			}, 
			{
				"show data transfer rate counter"
			,
				"affiche le taux de tranfert des données"
			}, 
			{
				"show data transfer average rate counter"
			,
				""
			}, 
			{
				"show number of bytes transferred"
			,
				"affiche le nombre d'octets transférés"
			}, 
			{
				"output even if standard error is not a terminal"
			,
				"imprime vers la sortie d'erreur même si ce n'est pas un terminal"
			}, 
			{
				"output percentages, not visual information"
			,
				"imprime en pourcentage, pas les informations visuelles"
			}, 
			{
				"do not output any transfer information at all"
			,
				"n'afficher aucune information de transfert"
			}, 
			{
				"use cursor positioning escape sequences"
			,
				"utiliser les séquences d'échappements de positionnement de curseur"
			}, 
			{
				"display nothing until first byte transferred"
			,
				"ne rien afficher avant qu'au moins un octet soit tranféré"
			}, 
			{
				"SIZE"
			,
				"TAILLE"
			}, 
			{
				"set estimated data size to SIZE bytes"
			,
				"ajuste la taille estimée des données à TAILLE octets"
			}, 
			{
				"count lines instead of bytes"
			,
				"compte les lignes au lieu des octets"
			}, 
			{
				"SEC"
			,
				"SEC"
			}, 
			{
				"update every SEC seconds"
			,
				"mise-à-jour toute les SEC secondes"
			}, 
			{
				"WIDTH"
			,
				"LARGEUR"
			}, 
			{
				"assume terminal is WIDTH characters wide"
			,
				"présumer la largeur du terminal à LARGEUR caractères"
			}, 
			{
				"HEIGHT"
			,
				"HAUTEUR"
			}, 
			{
				"assume terminal is HEIGHT rows high"
			,
				"présumer la hauteur du terminal à HAUTEUR lignes"
			}, 
			{
				"NAME"
			,
				"NOM"
			}, 
			{
				"prefix visual information with NAME"
			,
				"préfixer les informations visuelles avec NOM"
			}, 
			{
				"RATE"
			,
				"TAUX"
			}, 
			{
				"limit transfer to RATE bytes per second"
			,
				"limite le taux de transfer à TAUX octets par seconde"
			}, 
			{
				"BYTES"
			,
				"OCTETS"
			}, 
			{
				"use a buffer size of BYTES"
			,
				"Utiliser une mémoire tampon de OCTETS octets"
			}, 
			{
				"PID"
			,
				"PID"
			}, 
			{
				"update settings of process PID"
			,
				"mettre-à-jour la configuration du processus PID"
			}, 
			{
				"show this help and exit"
			,
				"afficher cette aide puis quitter"
			}, 
			{
				"show version information and exit"
			,
				"afficher la version puis quitter"
			}, 
			{
				"Usage: %s [OPTION] [FILE]..."
			,
				"Utilisation : %s [OPTIONS] [FICHIER]..."
			}, 
			{
				""
				"Concatenate FILE(s), or standard input, to standard output,\n"
				"with monitoring."
			,
				""
				"Concatène FICHIER(s), ou l'entrée standard, sur la sortie standard\n"
				"avec monitorage."
			}, 
			{
				"Please report any bugs to %s."
			,
				"SVP rapporter touts bogues à %s."
			}, 
			{
				"%s: option structure allocation failed (%s)"
			,
				"%s: l'allocation pour la structure d'une option a echoué (%s)"
			}, 
			{
				"%s: option structure argv allocation failed (%s)"
			,
				"%s: l'allocation pour la structure de l'option argv a echoué (%s)"
			}, 
			{
				"integer argument expected"
			,
				"Valeur entière attendue"
			}, 
			{
				"numeric argument expected"
			,
				"Valeur numérique attendue"
			}, 
			{
				"Try `%s --help' for more information."
			,
				"Essayez `%s --help' pour plus d'information."
			}, 
			{
				"Try `%s -h' for more information."
			,
				"Essayez `%s -h' pour plus d'information."
			}, 
			{
				"%s %s - Copyright(C) %s %s"
			,
				"%s %s - Copyright(C) %s %s"
			}, 
			{
				"Web site: %s"
			,
				"Site Web: %s"
			}, 
			{
				""
				"This program is free software, and is being distributed under the\n"
				"terms of the Artistic License 2.0."
			,
				""
				"Ce programme est un logiciel libre et est distribué sous les termes\n"
				"anglophone de la Licence Artistique 2.0 (Artistic License 2.0)."
			}, 
			{
				""
				"This program is distributed in the hope that it will be useful,\n"
				"but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
				"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
			,
				""
				"Ce programme est distribué dans l'espoir qu'il sera utile, mais\n"
				"SANS GARANTIE AUCUNE; ni même de garantie sous-entendu que le\n"
				"programme soit COMMERCIALISABLE ou APPLICABLE À UNE TÂCHE\n"
				"PARTICULIÈRE."
			}

			, { 0, 0 } };
		return data;
	}
	if (strncmp(lang, "pl", 2) == 0) {
		static struct msgtable_s data[] = {
			{
				""
			,
				""
				"Project-Id-Version: PACKAGE VERSION\n"
				"Report-Msgid-Bugs-To: \n"
				"POT-Creation-Date: 2010-12-14 10:06+0000\n"
				"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
				"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
				"Language-Team: LANGUAGE <LL@li.org>\n"
				"MIME-Version: 1.0\n"
				"Content-Type: text/plain; charset=ISO-8859-2\n"
				"Content-Transfer-Encoding: 8bit\n"
			}, 
			{
				"failed to close file"
			,
				"nie uda³o siê zamkn±æ pliku"
			}, 
			{
				"failed to read file"
			,
				"nie uda³o siê odczytaæ pliku"
			}, 
			{
				"failed to stat file"
			,
				"nie uda³o siê wykonaæ operacji stat na pliku"
			}, 
			{
				"failed to stat output file"
			,
				"nie uda³o siê wykonaæ operacji stat na pliku wyj¶ciowym"
			}, 
			{
				"input file is output file"
			,
				"plik wej¶ciowy jest zarazem plikiem wyj¶ciowym"
			}, 
			{
				"yzafpnum kMGTPEZY"
			,
				""
			}, 
			{
				"buffer allocation failed"
			,
				"nie uda³o siê zaalokowaæ bufora"
			}, 
			{
				"B"
			,
				"B"
			}, 
			{
				"/s"
			,
				"/s"
			}, 
			{
				"B/s"
			,
				"B/s"
			}, 
			{
				"ETA"
			,
				"ETA"
			}, 
			{
				"failed to open terminal"
			,
				"nie uda³o siê otworzyæ terminala"
			}, 
			{
				"failed to lock terminal"
			,
				"nie uda³o siê otworzyæ terminala"
			}, 
			{
				"select call failed"
			,
				"nie uda³o siê wywo³aæ funkcji select"
			}, 
			{
				"read failed"
			,
				"b³±d odczytu"
			}, 
			{
				"write failed"
			,
				"b³±d zapisu"
			}, 
			{
				"show progress bar"
			,
				"poka¿ pasek postêpu"
			}, 
			{
				"show elapsed time"
			,
				"poka¿ up³ywaj±cy czas"
			}, 
			{
				"show estimated time of arrival (completion)"
			,
				"poka¿ szacowany czas ukoñczenia"
			}, 
			{
				"show data transfer rate counter"
			,
				"poka¿ licznik prêdko¶ci przesy³ania"
			}, 
			{
				"show data transfer average rate counter"
			,
				""
			}, 
			{
				"show number of bytes transferred"
			,
				"poka¿ ilo¶æ przes³anych bajtów"
			}, 
			{
				"output even if standard error is not a terminal"
			,
				"poka¿ wyj¶cie nawet gdy b³êdy nie s± typu terminal"
			}, 
			{
				"output percentages, not visual information"
			,
				"w¶wietl wyj¶cie procentowo, bez graficznej prezentacji"
			}, 
			{
				"do not output any transfer information at all"
			,
				"nie wy¶wietlaj ¿adnych informacji o przesy³aniu"
			}, 
			{
				"use cursor positioning escape sequences"
			,
				"u¿ywaj sekwencji escape do pozycjonowania"
			}, 
			{
				"display nothing until first byte transferred"
			,
				"nie wy¶wietlaj nic a¿ do pierwszego przes³anego bajtu"
			}, 
			{
				"SIZE"
			,
				"WARTO¦Æ"
			}, 
			{
				"set estimated data size to SIZE bytes"
			,
				"ustaw oczekiwany rozmiar danych na WARTO¦Æ bajtów"
			}, 
			{
				"count lines instead of bytes"
			,
				""
			}, 
			{
				"SEC"
			,
				"WARTO¦Æ"
			}, 
			{
				"update every SEC seconds"
			,
				"aktualizuj co ka¿de WARTO¦Æ sekund"
			}, 
			{
				"WIDTH"
			,
				"WARTO¦Æ"
			}, 
			{
				"assume terminal is WIDTH characters wide"
			,
				"przyjmij, ¿e terminal ma szeroko¶æ WARTO¦Æ znaków"
			}, 
			{
				"HEIGHT"
			,
				""
			}, 
			{
				"assume terminal is HEIGHT rows high"
			,
				"przyjmij, ¿e terminal ma szeroko¶æ WARTO¦Æ znaków"
			}, 
			{
				"NAME"
			,
				"NAZWA"
			}, 
			{
				"prefix visual information with NAME"
			,
				"poprzed¼ informacje prefiksem NAZWA"
			}, 
			{
				"RATE"
			,
				""
			}, 
			{
				"limit transfer to RATE bytes per second"
			,
				"ogranicz przesy³ane dane do RATE bajtów na sekundê"
			}, 
			{
				"BYTES"
			,
				""
			}, 
			{
				"use a buffer size of BYTES"
			,
				""
			}, 
			{
				"PID"
			,
				""
			}, 
			{
				"update settings of process PID"
			,
				""
			}, 
			{
				"show this help and exit"
			,
				"wy¶wietl te informacje z pomoc± i wyjd¼"
			}, 
			{
				"show version information and exit"
			,
				"wy¶wietl informacje o wersji i wyjd¼"
			}, 
			{
				"Usage: %s [OPTION] [FILE]..."
			,
				"Sposób u¿ycia: %s [OPCJA] [PLIK]..."
			}, 
			{
				""
				"Concatenate FILE(s), or standard input, to standard output,\n"
				"with monitoring."
			,
				""
				"£±czenie PLIK(ów) lub wej¶cia standardowego, do wyj¶cia standardowego\n"
				"z monitoringiem."
			}, 
			{
				"Please report any bugs to %s."
			,
				"Proszê przesy³aæ zg³oszenia b³êdów do %s."
			}, 
			{
				"%s: option structure allocation failed (%s)"
			,
				"%s: nie uda³o siê zaalokowaæ struktur opcji (%s)"
			}, 
			{
				"%s: option structure argv allocation failed (%s)"
			,
				"%s: nie uda³o siê zaalokowaæ struktur opcji argv (%s)"
			}, 
			{
				"integer argument expected"
			,
				""
			}, 
			{
				"numeric argument expected"
			,
				""
			}, 
			{
				"Try `%s --help' for more information."
			,
				"Spróbuj `%s --help' by uzyskaæ wiêcej informacji"
			}, 
			{
				"Try `%s -h' for more information."
			,
				"Spróbuj `%s -h' by uzyskaæ wiêcej informacji"
			}, 
			{
				"%s %s - Copyright(C) %s %s"
			,
				"%s %s - Prawa autorskie (C) %s %s"
			}, 
			{
				"Web site: %s"
			,
				"Strona WWW: %s"
			}, 
			{
				""
				"This program is free software, and is being distributed under the\n"
				"terms of the Artistic License 2.0."
			,
				""
			}, 
			{
				""
				"This program is distributed in the hope that it will be useful,\n"
				"but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
				"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
			,
				""
			}

			, { 0, 0 } };
		return data;
	}
	if (strncmp(lang, "pt", 2) == 0) {
		static struct msgtable_s data[] = {
			{
				""
			,
				""
				"Project-Id-Version: PACKAGE VERSION\n"
				"Report-Msgid-Bugs-To: \n"
				"POT-Creation-Date: 2010-12-14 10:06+0000\n"
				"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
				"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
				"Language-Team: LANGUAGE <LL@li.org>\n"
				"MIME-Version: 1.0\n"
				"Content-Type: text/plain; charset=ISO-8859-15\n"
				"Content-Transfer-Encoding: 8bit\n"
			}, 
			{
				"failed to close file"
			,
				"erro fechando o arquivo"
			}, 
			{
				"failed to read file"
			,
				"erro lendo o arquivo"
			}, 
			{
				"failed to stat file"
			,
				"erro obtendo informações do arquivo"
			}, 
			{
				"failed to stat output file"
			,
				"erro obtendo informações do arquivo de saída"
			}, 
			{
				"input file is output file"
			,
				"os arquivos de entrada e saída são o mesmo"
			}, 
			{
				"yzafpnum kMGTPEZY"
			,
				""
			}, 
			{
				"buffer allocation failed"
			,
				"erro alocando o buffer"
			}, 
			{
				"B"
			,
				""
			}, 
			{
				"/s"
			,
				""
			}, 
			{
				"B/s"
			,
				"B/s"
			}, 
			{
				"ETA"
			,
				"ETA"
			}, 
			{
				"failed to open terminal"
			,
				"erro abrindo o terminal"
			}, 
			{
				"failed to lock terminal"
			,
				"erro abrindo o terminal"
			}, 
			{
				"select call failed"
			,
				"erro na chamada da função select"
			}, 
			{
				"read failed"
			,
				"erro de leitura"
			}, 
			{
				"write failed"
			,
				"erro de gravação"
			}, 
			{
				"show progress bar"
			,
				"exibe barra de progressão"
			}, 
			{
				"show elapsed time"
			,
				"exibe tempo passado"
			}, 
			{
				"show estimated time of arrival (completion)"
			,
				"exibe o tempo estimado de término"
			}, 
			{
				"show data transfer rate counter"
			,
				"exibe a taxa de transferência"
			}, 
			{
				"show data transfer average rate counter"
			,
				""
			}, 
			{
				"show number of bytes transferred"
			,
				"exibe a quantidade de bytes transferidos"
			}, 
			{
				"output even if standard error is not a terminal"
			,
				"gera dados mesmo que a saída de erro seja redirecionada"
			}, 
			{
				"output percentages, not visual information"
			,
				"exibe apenas as porcentagens, sem informações visuais"
			}, 
			{
				"do not output any transfer information at all"
			,
				"executa programa sem exibir quaisquer informações"
			}, 
			{
				"use cursor positioning escape sequences"
			,
				"utiliza caracteres de escape para posicionar o cursor"
			}, 
			{
				"display nothing until first byte transferred"
			,
				"não exibe nada até iniciar o processamento"
			}, 
			{
				"SIZE"
			,
				""
			}, 
			{
				"set estimated data size to SIZE bytes"
			,
				"seta a quantidade estimada de dados em SIZE bytes"
			}, 
			{
				"count lines instead of bytes"
			,
				""
			}, 
			{
				"SEC"
			,
				""
			}, 
			{
				"update every SEC seconds"
			,
				"atualiza informações a cada SEC segundos"
			}, 
			{
				"WIDTH"
			,
				""
			}, 
			{
				"assume terminal is WIDTH characters wide"
			,
				"assume que terminal possui WIDTH caracteres de largura"
			}, 
			{
				"HEIGHT"
			,
				""
			}, 
			{
				"assume terminal is HEIGHT rows high"
			,
				"assume que terminal possui WIDTH caracteres de largura"
			}, 
			{
				"NAME"
			,
				""
			}, 
			{
				"prefix visual information with NAME"
			,
				"exibe NAME antes das demais informações"
			}, 
			{
				"RATE"
			,
				""
			}, 
			{
				"limit transfer to RATE bytes per second"
			,
				"limita a transferência a RATE bytes por segundo"
			}, 
			{
				"BYTES"
			,
				""
			}, 
			{
				"use a buffer size of BYTES"
			,
				""
			}, 
			{
				"PID"
			,
				""
			}, 
			{
				"update settings of process PID"
			,
				""
			}, 
			{
				"show this help and exit"
			,
				"exibe esta tela de ajuda e termina"
			}, 
			{
				"show version information and exit"
			,
				"exibe a versão e termina"
			}, 
			{
				"Usage: %s [OPTION] [FILE]..."
			,
				"Uso: %s [OPÇÕES] [ARQUIVOS]..."
			}, 
			{
				""
				"Concatenate FILE(s), or standard input, to standard output,\n"
				"with monitoring."
			,
				""
				"Concatena ARQUIVO(s) ou a entrada padrão e grava na saída padrão,\n"
				"com monitoramento."
			}, 
			{
				"Please report any bugs to %s."
			,
				"Por favor, reporte quaisquer defeitos para %s."
			}, 
			{
				"%s: option structure allocation failed (%s)"
			,
				"%s: erro na alocação da estrutura de opções (%s)"
			}, 
			{
				"%s: option structure argv allocation failed (%s)"
			,
				"%s: erro na alocação da estrutura de opções argv (%s)"
			}, 
			{
				"integer argument expected"
			,
				""
			}, 
			{
				"numeric argument expected"
			,
				""
			}, 
			{
				"Try `%s --help' for more information."
			,
				"Tente `%s --help' para maiores informações."
			}, 
			{
				"Try `%s -h' for more information."
			,
				"Tente `%s -h' para maiores informações."
			}, 
			{
				"%s %s - Copyright(C) %s %s"
			,
				"%s %s - Copyright(C) %s %s"
			}, 
			{
				"Web site: %s"
			,
				"Site: %s"
			}, 
			{
				""
				"This program is free software, and is being distributed under the\n"
				"terms of the Artistic License 2.0."
			,
				""
				"Este programa é um software livre, distribuído sob os termos da\n"
				"Licença Artística."
			}, 
			{
				""
				"This program is distributed in the hope that it will be useful,\n"
				"but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
				"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
			,
				""
				"Este programa é distribuído com o intuito de que seja útil,\n"
				"porém SEM QUAISQUER GARANTIAS; sem inclusive as garantias implícitas de\n"
				"COMERCIALIZAÇÃO e ADEQUAÇÃO A OBJETIVOS PARTICULARES."
			}

			, { 0, 0 } };
		return data;
	}

	return 0;
}

/* EOF */
